// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQvVN5if546VqLUYl5fk_3tdsCBSyyV5w',
    appId: '1:661033945144:web:721058dccac5b964d93ecd',
    messagingSenderId: '661033945144',
    projectId: 'information-technology-143ab',
    authDomain: 'information-technology-143ab.firebaseapp.com',
    storageBucket: 'information-technology-143ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAeFa2xLq3s_J3ANiCZ08qtwi30Oyscgc',
    appId: '1:661033945144:android:3918a3315de5388bd93ecd',
    messagingSenderId: '661033945144',
    projectId: 'information-technology-143ab',
    storageBucket: 'information-technology-143ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIg89bpguVxLc2DAxUCn6j7B1Tg1KsYNw',
    appId: '1:661033945144:ios:6a9081ab61d11345d93ecd',
    messagingSenderId: '661033945144',
    projectId: 'information-technology-143ab',
    storageBucket: 'information-technology-143ab.firebasestorage.app',
    iosBundleId: 'com.example.informationTechnology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIg89bpguVxLc2DAxUCn6j7B1Tg1KsYNw',
    appId: '1:661033945144:ios:6a9081ab61d11345d93ecd',
    messagingSenderId: '661033945144',
    projectId: 'information-technology-143ab',
    storageBucket: 'information-technology-143ab.firebasestorage.app',
    iosBundleId: 'com.example.informationTechnology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQvVN5if546VqLUYl5fk_3tdsCBSyyV5w',
    appId: '1:661033945144:web:b666e3f0ff2c2e7bd93ecd',
    messagingSenderId: '661033945144',
    projectId: 'information-technology-143ab',
    authDomain: 'information-technology-143ab.firebaseapp.com',
    storageBucket: 'information-technology-143ab.firebasestorage.app',
  );
}
